# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Files\Maker\Code\CommonMinecraftLauncher-PyQT\CMCLv2\QtUi\AccountCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(928, 80)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ElevatedCardWidget = ElevatedCardWidget(Form)
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.ElevatedCardWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ImageLabel = ImageLabel(self.ElevatedCardWidget)
        self.ImageLabel.setObjectName("ImageLabel")
        self.gridLayout.addWidget(self.ImageLabel, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.ElevatedCardWidget)
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 0, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel_Name = BodyLabel(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("MiSans")
        font.setPointSize(14)
        font.setBold(False)
        self.BodyLabel_Name.setFont(font)
        self.BodyLabel_Name.setObjectName("BodyLabel_Name")
        self.verticalLayout.addWidget(self.BodyLabel_Name)
        self.CaptionLabel = CaptionLabel(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        self.CaptionLabel.setFont(font)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.verticalLayout.addWidget(self.CaptionLabel)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.PushButton_Delete = PushButton(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(False)
        self.PushButton_Delete.setFont(font)
        self.PushButton_Delete.setObjectName("PushButton_Delete")
        self.horizontalLayout_3.addWidget(self.PushButton_Delete)
        self.horizontalLayout_3.setStretch(0, 10)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.CardWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BodyLabel_Name.setText(_translate("Form", "Name"))
        self.CaptionLabel.setText(_translate("Form", "正版登录"))
        self.PushButton_Delete.setText(_translate("Form", "删除"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, ElevatedCardWidget, ImageLabel, PushButton
