# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Files\Maker\Code\CommonMinecraftLauncher-PyQT\CMCLv2\QtUi\AboutPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(948, 519)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLabel = BodyLabel(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("MiSans Medium")
        font.setPointSize(13)
        font.setBold(False)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_4.addWidget(self.BodyLabel)
        self.label = QtWidgets.QLabel(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HyperlinkButton_OpenSite = HyperlinkButton(self.CardWidget)
        self.HyperlinkButton_OpenSite.setObjectName("HyperlinkButton_OpenSite")
        self.horizontalLayout.addWidget(self.HyperlinkButton_OpenSite)
        self.HyperlinkButton_JoinGroup = HyperlinkButton(self.CardWidget)
        self.HyperlinkButton_JoinGroup.setObjectName("HyperlinkButton_JoinGroup")
        self.horizontalLayout.addWidget(self.HyperlinkButton_JoinGroup)
        self.TransparentPushButton_Github = TransparentPushButton(self.CardWidget)
        self.TransparentPushButton_Github.setObjectName("TransparentPushButton_Github")
        self.horizontalLayout.addWidget(self.TransparentPushButton_Github)
        self.TransparentPushButton_ColoredEgg = TransparentPushButton(self.CardWidget)
        self.TransparentPushButton_ColoredEgg.setObjectName("TransparentPushButton_ColoredEgg")
        self.horizontalLayout.addWidget(self.TransparentPushButton_ColoredEgg)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout.addWidget(self.CardWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BodyLabel.setText(_translate("Form", "▌关于"))
        self.HyperlinkButton_OpenSite.setText(_translate("Form", "官网"))
        self.HyperlinkButton_JoinGroup.setText(_translate("Form", "加入官方QQ群"))
        self.TransparentPushButton_Github.setText(_translate("Form", "Github"))
        self.TransparentPushButton_ColoredEgg.setText(_translate("Form", "??"))
from qfluentwidgets import BodyLabel, CardWidget, HyperlinkButton, TransparentPushButton
